import { Uf } from '../entities/oracle/uf.entity';

export const ufMocks: Partial<Uf>[] = [
  {
    codUfIbge: '11',
    sgUf: 'RO',
    codRegion: '1',
    codCountry: 1,
    nameUf: 'Rondônia',
    codUfSinpas: '23',
    numArea: 237765.347,
    codUfldo: '0011',
    numLatitude: '-10.83',
    codUfInss: '23',
    codUfSiafi: '04',
    numLongitude: '-63.34',
    numOrderRegion: 1,
    dsNatural: 'rondoniense',
    codCityIbgeCapital: '110020',
    stActiveRegistry: 'S',
    codStateSvs: 11,
    numUfMarked: 'Rondônia',
    codIso31662: 'BR-RO',
    stCadSus: 'S',
  },
  {
    codUfIbge: '12',
    sgUf: 'AC',
    codRegion: '1',
    codCountry: 1,
    nameUf: 'Acre',
    codUfSinpas: '24',
    numArea: 164123.964,
    codUfldo: '0012',
    numLatitude: '-8.77',
    codUfInss: '24',
    codUfSiafi: '01',
    numLongitude: '-70.55',
    numOrderRegion: 2,
    dsNatural: 'acreano',
    codCityIbgeCapital: '120040',
    stActiveRegistry: 'S',
    codStateSvs: 12,
    numUfMarked: 'Acre',
    codIso31662: 'BR-AC',
    stCadSus: 'S',
  },
  {
    codUfIbge: '13',
    sgUf: 'AM',
    codRegion: '1',
    codCountry: 1,
    nameUf: 'Amazonas',
    codUfSinpas: '25',
    numArea: 1559167.878,
    codUfldo: '0013',
    numLatitude: '-3.47',
    codUfInss: '25',
    codUfSiafi: '02',
    numLongitude: '-65.10',
    numOrderRegion: 3,
    dsNatural: 'amazonense',
    codCityIbgeCapital: '130260',
    stActiveRegistry: 'S',
    codStateSvs: 13,
    numUfMarked: 'Amazonas',
    codIso31662: 'BR-AM',
    stCadSus: 'S',
  },
  {
    codUfIbge: '14',
    sgUf: 'RR',
    codRegion: '1',
    codCountry: 1,
    nameUf: 'Roraima',
    codUfSinpas: '26',
    numArea: 224299.544,
    codUfldo: '0014',
    numLatitude: '2.74',
    codUfInss: '26',
    codUfSiafi: '23',
    numLongitude: '-62.07',
    numOrderRegion: 4,
    dsNatural: 'roraimense',
    codCityIbgeCapital: '140010',
    stActiveRegistry: 'S',
    codStateSvs: 14,
    numUfMarked: 'Roraima',
    codIso31662: 'BR-RR',
    stCadSus: 'S',
  },
  {
    codUfIbge: '15',
    sgUf: 'PA',
    codRegion: '1',
    codCountry: 1,
    nameUf: 'Pará',
    codUfSinpas: '27',
    numArea: 1247954.666,
    codUfldo: '0015',
    numLatitude: '-1.99',
    codUfInss: '27',
    codUfSiafi: '14',
    numLongitude: '-54.93',
    numOrderRegion: 5,
    dsNatural: 'paraense',
    codCityIbgeCapital: '150140',
    stActiveRegistry: 'S',
    codStateSvs: 15,
    numUfMarked: 'Pará',
    codIso31662: 'BR-PA',
    stCadSus: 'S',
  },
  {
    codUfIbge: '16',
    sgUf: 'AP',
    codRegion: '1',
    codCountry: 1,
    nameUf: 'Amapá',
    codUfSinpas: '28',
    numArea: 142827.897,
    codUfldo: '0016',
    numLatitude: '1.41',
    codUfInss: '28',
    codUfSiafi: '03',
    numLongitude: '-51.77',
    numOrderRegion: 6,
    dsNatural: 'amapaense',
    codCityIbgeCapital: '160030',
    stActiveRegistry: 'S',
    codStateSvs: 16,
    numUfMarked: 'Amapá',
    codIso31662: 'BR-AP',
    stCadSus: 'S',
  },
  {
    codUfIbge: '17',
    sgUf: 'TO',
    codRegion: '1',
    codCountry: 1,
    nameUf: 'Tocantins',
    codUfSinpas: '29',
    numArea: 277720.52,
    codUfldo: '0017',
    numLatitude: '-10.17',
    codUfInss: '29',
    codUfSiafi: '27',
    numLongitude: '-48.29',
    numOrderRegion: 7,
    dsNatural: 'tocantinense',
    codCityIbgeCapital: '172100',
    stActiveRegistry: 'S',
    codStateSvs: 17,
    numUfMarked: 'Tocantins',
    codIso31662: 'BR-TO',
    stCadSus: 'S',
  },
  {
    codUfIbge: '21',
    sgUf: 'MA',
    codRegion: '2',
    codCountry: 1,
    nameUf: 'Maranhão',
    codUfSinpas: '10',
    numArea: 331937.45,
    codUfldo: '0021',
    numLatitude: '-4.96',
    codUfInss: '10',
    codUfSiafi: '13',
    numLongitude: '-45.27',
    numOrderRegion: 1,
    dsNatural: 'maranhense',
    codCityIbgeCapital: '211130',
    stActiveRegistry: 'S',
    codStateSvs: 21,
    numUfMarked: 'Maranhão',
    codIso31662: 'BR-MA',
    stCadSus: 'S',
  },
  {
    codUfIbge: '22',
    sgUf: 'PI',
    codRegion: '2',
    codCountry: 1,
    nameUf: 'Piauí',
    codUfSinpas: '11',
    numArea: 251577.738,
    codUfldo: '0022',
    numLatitude: '-7.72',
    codUfInss: '11',
    codUfSiafi: '16',
    numLongitude: '-42.72',
    numOrderRegion: 2,
    dsNatural: 'piauiense',
    codCityIbgeCapital: '221100',
    stActiveRegistry: 'S',
    codStateSvs: 22,
    numUfMarked: 'Piauí',
    codIso31662: 'BR-PI',
    stCadSus: 'S',
  },
  {
    codUfIbge: '23',
    sgUf: 'CE',
    codRegion: '2',
    codCountry: 1,
    nameUf: 'Ceará',
    codUfSinpas: '12',
    numArea: 148920.472,
    codUfldo: '0023',
    numLatitude: '-5.49',
    codUfInss: '12',
    codUfSiafi: '06',
    numLongitude: '-39.32',
    numOrderRegion: 3,
    dsNatural: 'cearense',
    codCityIbgeCapital: '230440',
    stActiveRegistry: 'S',
    codStateSvs: 23,
    numUfMarked: 'Ceará',
    codIso31662: 'BR-CE',
    stCadSus: 'S',
  },
  {
    codUfIbge: '24',
    sgUf: 'RN',
    codRegion: '2',
    codCountry: 1,
    nameUf: 'Rio Grande do Norte',
    codUfSinpas: '13',
    numArea: 52811.107,
    codUfldo: '0024',
    numLatitude: '-5.81',
    codUfInss: '13',
    codUfSiafi: '20',
    numLongitude: '-36.59',
    numOrderRegion: 4,
    dsNatural: 'potiguar',
    codCityIbgeCapital: '240810',
    stActiveRegistry: 'S',
    codStateSvs: 24,
    numUfMarked: 'Rio Grande do Norte',
    codIso31662: 'BR-RN',
    stCadSus: 'S',
  },
  {
    codUfIbge: '25',
    sgUf: 'PB',
    codRegion: '2',
    codCountry: 1,
    nameUf: 'Paraíba',
    codUfSinpas: '14',
    numArea: 56468.435,
    codUfldo: '0025',
    numLatitude: '-7.24',
    codUfInss: '14',
    codUfSiafi: '15',
    numLongitude: '-36.72',
    numOrderRegion: 5,
    dsNatural: 'paraibano',
    codCityIbgeCapital: '250750',
    stActiveRegistry: 'S',
    codStateSvs: 25,
    numUfMarked: 'Paraíba',
    codIso31662: 'BR-PB',
    stCadSus: 'S',
  },
  {
    codUfIbge: '26',
    sgUf: 'PE',
    codRegion: '2',
    codCountry: 1,
    nameUf: 'Pernambuco',
    codUfSinpas: '15',
    numArea: 98148.323,
    codUfldo: '0026',
    numLatitude: '-8.38',
    codUfInss: '15',
    codUfSiafi: '10',
    numLongitude: '-37.86',
    numOrderRegion: 6,
    dsNatural: 'pernambucano',
    codCityIbgeCapital: '261160',
    stActiveRegistry: 'S',
    codStateSvs: 26,
    numUfMarked: 'Pernambuco',
    codIso31662: 'BR-PE',
    stCadSus: 'S',
  },
  {
    codUfIbge: '27',
    sgUf: 'AL',
    codRegion: '2',
    codCountry: 1,
    nameUf: 'Alagoas',
    codUfSinpas: '16',
    numArea: 27778.506,
    codUfldo: '0027',
    numLatitude: '-9.57',
    codUfInss: '16',
    codUfSiafi: '05',
    numLongitude: '-36.78',
    numOrderRegion: 7,
    dsNatural: 'alagoano',
    codCityIbgeCapital: '270430',
    stActiveRegistry: 'S',
    codStateSvs: 27,
    numUfMarked: 'Alagoas',
    codIso31662: 'BR-AL',
    stCadSus: 'S',
  },
  {
    codUfIbge: '28',
    sgUf: 'SE',
    codRegion: '2',
    codCountry: 1,
    nameUf: 'Sergipe',
    codUfSinpas: '17',
    numArea: 21918.443,
    codUfldo: '0028',
    numLatitude: '-10.57',
    codUfInss: '17',
    codUfSiafi: '25',
    numLongitude: '-37.45',
    numOrderRegion: 8,
    dsNatural: 'sergipano',
    codCityIbgeCapital: '280030',
    stActiveRegistry: 'S',
    codStateSvs: 28,
    numUfMarked: 'Sergipe',
    codIso31662: 'BR-SE',
    stCadSus: 'S',
  },
  {
    codUfIbge: '29',
    sgUf: 'BA',
    codRegion: '2',
    codCountry: 1,
    nameUf: 'Bahia',
    codUfSinpas: '18',
    numArea: 564733.177,
    codUfldo: '0029',
    numLatitude: '-12.58',
    codUfInss: '18',
    codUfSiafi: '05',
    numLongitude: '-41.70',
    numOrderRegion: 9,
    dsNatural: 'baiano',
    codCityIbgeCapital: '292740',
    stActiveRegistry: 'S',
    codStateSvs: 29,
    numUfMarked: 'Bahia',
    codIso31662: 'BR-BA',
    stCadSus: 'S',
  },
  {
    codUfIbge: '31',
    sgUf: 'MG',
    codRegion: '3',
    codCountry: 1,
    nameUf: 'Minas Gerais',
    codUfSinpas: '05',
    numArea: 586521.121,
    codUfldo: '0031',
    numLatitude: '-18.51',
    codUfInss: '05',
    codUfSiafi: '13',
    numLongitude: '-44.55',
    numOrderRegion: 1,
    dsNatural: 'mineiro',
    codCityIbgeCapital: '310620',
    stActiveRegistry: 'S',
    codStateSvs: 31,
    numUfMarked: 'Minas Gerais',
    codIso31662: 'BR-MG',
    stCadSus: 'S',
  },
  {
    codUfIbge: '32',
    sgUf: 'ES',
    codRegion: '3',
    codCountry: 1,
    nameUf: 'Espírito Santo',
    codUfSinpas: '06',
    numArea: 46095.583,
    codUfldo: '0032',
    numLatitude: '-19.19',
    codUfInss: '06',
    codUfSiafi: '08',
    numLongitude: '-40.34',
    numOrderRegion: 2,
    dsNatural: 'capixaba',
    codCityIbgeCapital: '320530',
    stActiveRegistry: 'S',
    codStateSvs: 32,
    numUfMarked: 'Espírito Santo',
    codIso31662: 'BR-ES',
    stCadSus: 'S',
  },
  {
    codUfIbge: '33',
    sgUf: 'RJ',
    codRegion: '3',
    codCountry: 1,
    nameUf: 'Rio de Janeiro',
    codUfSinpas: '07',
    numArea: 43780.172,
    codUfldo: '0033',
    numLatitude: '-22.25',
    codUfInss: '07',
    codUfSiafi: '19',
    numLongitude: '-42.66',
    numOrderRegion: 3,
    dsNatural: 'fluminense',
    codCityIbgeCapital: '330455',
    stActiveRegistry: 'S',
    codStateSvs: 33,
    numUfMarked: 'Rio de Janeiro',
    codIso31662: 'BR-RJ',
    stCadSus: 'S',
  },
  {
    codUfIbge: '35',
    sgUf: 'SP',
    codRegion: '3',
    codCountry: 1,
    nameUf: 'São Paulo',
    codUfSinpas: '09',
    numArea: 248219.481,
    codUfldo: '0035',
    numLatitude: '-22.19',
    codUfInss: '09',
    codUfSiafi: '26',
    numLongitude: '-48.79',
    numOrderRegion: 4,
    dsNatural: 'paulista',
    codCityIbgeCapital: '355030',
    stActiveRegistry: 'S',
    codStateSvs: 35,
    numUfMarked: 'São Paulo',
    codIso31662: 'BR-SP',
    stCadSus: 'S',
  },
  {
    codUfIbge: '41',
    sgUf: 'PR',
    codRegion: '4',
    codCountry: 1,
    nameUf: 'Paraná',
    codUfSinpas: '01',
    numArea: 199307.922,
    codUfldo: '0041',
    numLatitude: '-25.25',
    codUfInss: '01',
    codUfSiafi: '75',
    numLongitude: '-52.02',
    numOrderRegion: 1,
    dsNatural: 'paranaense',
    codCityIbgeCapital: '410690',
    stActiveRegistry: 'S',
    codStateSvs: 41,
    numUfMarked: 'Paraná',
    codIso31662: 'BR-PR',
    stCadSus: 'S',
  },
  {
    codUfIbge: '42',
    sgUf: 'SC',
    codRegion: '4',
    codCountry: 1,
    nameUf: 'Santa Catarina',
    codUfSinpas: '02',
    numArea: 95736.165,
    codUfldo: '0042',
    numLatitude: '-27.45',
    codUfInss: '02',
    codUfSiafi: '24',
    numLongitude: '-50.95',
    numOrderRegion: 2,
    dsNatural: 'catarinense',
    codCityIbgeCapital: '420540',
    stActiveRegistry: 'S',
    codStateSvs: 42,
    numUfMarked: 'Santa Catarina',
    codIso31662: 'BR-SC',
    stCadSus: 'S',
  },
  {
    codUfIbge: '43',
    sgUf: 'RS',
    codRegion: '4',
    codCountry: 1,
    nameUf: 'Rio Grande do Sul',
    codUfSinpas: '03',
    numArea: 281730.223,
    codUfldo: '0043',
    numLatitude: '-30.17',
    codUfInss: '03',
    codUfSiafi: '23',
    numLongitude: '-53.50',
    numOrderRegion: 3,
    dsNatural: 'gaúcho',
    codCityIbgeCapital: '431490',
    stActiveRegistry: 'S',
    codStateSvs: 43,
    numUfMarked: 'Rio Grande do Sul',
    codIso31662: 'BR-RS',
    stCadSus: 'S',
  },
  {
    codUfIbge: '50',
    sgUf: 'MS',
    codRegion: '5',
    codCountry: 1,
    nameUf: 'Mato Grosso do Sul',
    codUfSinpas: '19',
    numArea: 357145.836,
    codUfldo: '0050',
    numLatitude: '-20.77',
    codUfInss: '19',
    codUfSiafi: '28',
    numLongitude: '-54.78',
    numOrderRegion: 1,
    dsNatural: 'sul-mato-grossense',
    codCityIbgeCapital: '500270',
    stActiveRegistry: 'S',
    codStateSvs: 50,
    numUfMarked: 'Mato Grosso do Sul',
    codIso31662: 'BR-MS',
    stCadSus: 'S',
  },
  {
    codUfIbge: '51',
    sgUf: 'MT',
    codRegion: '5',
    codCountry: 1,
    nameUf: 'Mato Grosso',
    codUfSinpas: '20',
    numArea: 903206.997,
    codUfldo: '0051',
    numLatitude: '-12.64',
    codUfInss: '20',
    codUfSiafi: '11',
    numLongitude: '-56.09',
    numOrderRegion: 2,
    dsNatural: 'mato-grossense',
    codCityIbgeCapital: '510340',
    stActiveRegistry: 'S',
    codStateSvs: 51,
    numUfMarked: 'Mato Grosso',
    codIso31662: 'BR-MT',
    stCadSus: 'S',
  },
  {
    codUfIbge: '52',
    sgUf: 'GO',
    codRegion: '5',
    codCountry: 1,
    nameUf: 'Goiás',
    codUfSinpas: '21',
    numArea: 340111.783,
    codUfldo: '0052',
    numLatitude: '-15.82',
    codUfInss: '21',
    codUfSiafi: '09',
    numLongitude: '-49.86',
    numOrderRegion: 3,
    dsNatural: 'goiano',
    codCityIbgeCapital: '520870',
    stActiveRegistry: 'S',
    codStateSvs: 52,
    numUfMarked: 'Goiás',
    codIso31662: 'BR-GO',
    stCadSus: 'S',
  },
  {
    codUfIbge: '53',
    sgUf: 'DF',
    codRegion: '5',
    codCountry: 1,
    nameUf: 'Distrito Federal',
    codUfSinpas: '22',
    numArea: 5779.999,
    codUfldo: '0053',
    numLatitude: '-15.83',
    codUfInss: '22',
    codUfSiafi: '07',
    numLongitude: '-47.86',
    numOrderRegion: 4,
    dsNatural: 'brasiliense',
    codCityIbgeCapital: '530010',
    stActiveRegistry: 'S',
    codStateSvs: 53,
    numUfMarked: 'Distrito Federal',
    codIso31662: 'BR-DF',
    stCadSus: 'S',
  },
];
