import { MigrationInterface, QueryRunner } from "typeorm";

export class AddAccreditationFields1766844987598 implements MigrationInterface {
    name = 'AddAccreditationFields1766844987598'

    public async up(queryRunner: QueryRunner): Promise<void> {
        // Verificar se a tabela TB_MOTIVO_CREDENCIAMENTO já existe (pode ter sido criada pelo seed)
        const motivoTableExists = await queryRunner.query(`
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'TB_MOTIVO_CREDENCIAMENTO'
            );
        `);
        
        if (!motivoTableExists[0].exists) {
            await queryRunner.query(`CREATE TABLE "TB_MOTIVO_CREDENCIAMENTO" ("CO_SEQ_DOM_MOTIVO_CRED" SERIAL NOT NULL, "CO_MOTIVO_CRED" character varying(80) NOT NULL, "DS_MOTIVO_CRED" character varying(255) NOT NULL, CONSTRAINT "PK_9874408050d0a6900d51e033e5f" PRIMARY KEY ("CO_SEQ_DOM_MOTIVO_CRED")); COMMENT ON COLUMN "TB_MOTIVO_CREDENCIAMENTO"."CO_MOTIVO_CRED" IS 'Código do motivo (chave negocial). Ex.: NAO_RENOVOU_RTA.'; COMMENT ON COLUMN "TB_MOTIVO_CREDENCIAMENTO"."DS_MOTIVO_CRED" IS 'Descrição do motivo de credenciamento/descredenciamento.'`);
            await queryRunner.query(`CREATE UNIQUE INDEX "IDX_184c3a2d02de0469258582257c" ON "TB_MOTIVO_CREDENCIAMENTO" ("CO_MOTIVO_CRED") `);
            await queryRunner.query(`COMMENT ON TABLE "TB_MOTIVO_CREDENCIAMENTO" IS 'Tabela de domínio de Motivos de Credenciamento/Descredenciamento da Farmácia. Utilizada como lista de valores estável em FK.'`);
        } else {
            // Se a tabela já existe, apenas criar o índice se não existir
            const indexExists = await queryRunner.query(`
                SELECT EXISTS (
                    SELECT FROM pg_indexes 
                    WHERE schemaname = 'public' 
                    AND indexname = 'IDX_184c3a2d02de0469258582257c'
                );
            `);
            if (!indexExists[0].exists) {
                await queryRunner.query(`CREATE UNIQUE INDEX "IDX_184c3a2d02de0469258582257c" ON "TB_MOTIVO_CREDENCIAMENTO" ("CO_MOTIVO_CRED") `);
            }
        }
        
        // Verificar se a tabela TB_FARMACIA_CREDENCIAMENTO já existe
        const credenciamentoTableExists = await queryRunner.query(`
            SELECT EXISTS (
                SELECT FROM information_schema.tables 
                WHERE table_schema = 'public' 
                AND table_name = 'TB_FARMACIA_CREDENCIAMENTO'
            );
        `);
        
        if (!credenciamentoTableExists[0].exists) {
            await queryRunner.query(`CREATE TABLE "TB_FARMACIA_CREDENCIAMENTO" ("CO_SEQ_FARMACIA_CRED" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL, "CO_FARMACIA" bigint NOT NULL, "ST_SITUACAO_CRED" character varying(10) NOT NULL, "CO_MOTIVO_CRED" character varying(80), "DS_NUP_SIPAR" character varying(255) NOT NULL, "DT_PUBLICACAO_DOU" date NOT NULL, "NU_SECAO_DOU" character varying(50), "NU_PAGINA_INICIAL" integer, "NU_PAGINA_FINAL" integer, "DS_ANEXOS" jsonb, "DS_VERSAO_MAQUINA" character varying(50) NOT NULL DEFAULT 'CREDENCIAMENTO@1', "DS_XSTATE_SNAPSHOT" jsonb, "CO_USUARIO_ATUALIZACAO" uuid, "DT_ATUALIZACAO" TIMESTAMP WITH TIME ZONE, "NU_ROW_VERSION" integer NOT NULL DEFAULT 1, CONSTRAINT "PK_8d858ee00d9660cd51ded6232f3" PRIMARY KEY ("CO_SEQ_FARMACIA_CRED")); COMMENT ON COLUMN "TB_FARMACIA_CREDENCIAMENTO"."CO_FARMACIA" IS 'Identificador da farmácia (FK lógica para a entidade de farmácia no domínio).'; COMMENT ON COLUMN "TB_FARMACIA_CREDENCIAMENTO"."ST_SITUACAO_CRED" IS 'Situação atual do credenciamento. Domínio: ATIVA / INATIVA.'; COMMENT ON COLUMN "TB_FARMACIA_CREDENCIAMENTO"."CO_MOTIVO_CRED" IS 'Motivo atual (FK para TB_DOM_MOTIVO_CREDENCIAMENTO.CO_MOTIVO_CRED). Pode ser nulo quando ainda não houve alteração registrada.'; COMMENT ON COLUMN "TB_FARMACIA_CREDENCIAMENTO"."DS_NUP_SIPAR" IS 'Número do Processo SEI/SIPAR (obrigatório conforme regra de negócio Item 18).'; COMMENT ON COLUMN "TB_FARMACIA_CREDENCIAMENTO"."DT_PUBLICACAO_DOU" IS 'Data da portaria no DOU (obrigatório conforme regra de negócio RN016).'; COMMENT ON COLUMN "TB_FARMACIA_CREDENCIAMENTO"."NU_SECAO_DOU" IS 'Seção do DOU.'; COMMENT ON COLUMN "TB_FARMACIA_CREDENCIAMENTO"."NU_PAGINA_INICIAL" IS 'Página inicial da publicação no DOU.'; COMMENT ON COLUMN "TB_FARMACIA_CREDENCIAMENTO"."NU_PAGINA_FINAL" IS 'Página final da publicação no DOU.'; COMMENT ON COLUMN "TB_FARMACIA_CREDENCIAMENTO"."DS_ANEXOS" IS 'Documentos comprobatórios (referências aos arquivos anexos).'; COMMENT ON COLUMN "TB_FARMACIA_CREDENCIAMENTO"."DS_VERSAO_MAQUINA" IS 'Versão do statechart (controle de compatibilidade/migração do snapshot do workflow).'; COMMENT ON COLUMN "TB_FARMACIA_CREDENCIAMENTO"."DS_XSTATE_SNAPSHOT" IS 'Snapshot persistido do workflow XState (jsonb). Usado para restaurar o actor e continuar o processamento.'; COMMENT ON COLUMN "TB_FARMACIA_CREDENCIAMENTO"."CO_USUARIO_ATUALIZACAO" IS 'Identificador do usuário responsável pela última atualização do estado.'; COMMENT ON COLUMN "TB_FARMACIA_CREDENCIAMENTO"."DT_ATUALIZACAO" IS 'Data e hora da última atualização do estado de credenciamento.'; COMMENT ON COLUMN "TB_FARMACIA_CREDENCIAMENTO"."NU_ROW_VERSION" IS 'Controle de concorrência otimista (incrementado em updates) para evitar race condition em transições.'`);
            await queryRunner.query(`CREATE UNIQUE INDEX "UK_TB_FARMACIA_CRED_CO_FARMACIA" ON "TB_FARMACIA_CREDENCIAMENTO" ("CO_FARMACIA") `);
            await queryRunner.query(`COMMENT ON TABLE "TB_FARMACIA_CREDENCIAMENTO" IS 'Armazena o estado atual de credenciamento da farmácia (situação e motivo) e o snapshot persistido do workflow XState para retomada entre requisições.'`);
        }
        
        // Verificar se a coluna CO_SEQ_FARMACIA já existe na tabela TB_FARMACIA
        const colExists = await queryRunner.query(`
            SELECT EXISTS (
                SELECT FROM information_schema.columns 
                WHERE table_schema = 'public' 
                AND table_name = 'TB_FARMACIA' 
                AND column_name = 'CO_SEQ_FARMACIA'
            );
        `);
        
        if (!colExists[0].exists) {
            await queryRunner.query(`ALTER TABLE "TB_FARMACIA" ADD "CO_SEQ_FARMACIA" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL`);
            
            // Verificar se a constraint PK antiga existe antes de dropar
            const oldPKExists = await queryRunner.query(`
                SELECT EXISTS (
                    SELECT FROM information_schema.table_constraints 
                    WHERE constraint_schema = 'public' 
                    AND constraint_name = 'PK_7737db16f908866a049c1aae729'
                );
            `);
            
            if (oldPKExists[0].exists) {
                await queryRunner.query(`ALTER TABLE "TB_FARMACIA" DROP CONSTRAINT "PK_7737db16f908866a049c1aae729"`);
                await queryRunner.query(`ALTER TABLE "TB_FARMACIA" ADD CONSTRAINT "PK_7524b5e083554075ecaa67cfff5" PRIMARY KEY ("NU_CNPJ", "CO_SEQ_FARMACIA")`);
                await queryRunner.query(`ALTER TABLE "TB_FARMACIA" DROP CONSTRAINT "PK_7524b5e083554075ecaa67cfff5"`);
            }
            
            // Verificar se a nova PK já existe
            const newPKExists = await queryRunner.query(`
                SELECT EXISTS (
                    SELECT FROM information_schema.table_constraints 
                    WHERE constraint_schema = 'public' 
                    AND constraint_name = 'PK_c25fd48ad34644edccea4dc40df'
                );
            `);
            
            if (!newPKExists[0].exists) {
                await queryRunner.query(`ALTER TABLE "TB_FARMACIA" ADD CONSTRAINT "PK_c25fd48ad34644edccea4dc40df" PRIMARY KEY ("CO_SEQ_FARMACIA")`);
            }
            
            // Verificar se a constraint unique já existe
            const uniqueExists = await queryRunner.query(`
                SELECT EXISTS (
                    SELECT FROM information_schema.table_constraints 
                    WHERE constraint_schema = 'public' 
                    AND constraint_name = 'UQ_7737db16f908866a049c1aae729'
                );
            `);
            
            if (!uniqueExists[0].exists) {
                await queryRunner.query(`ALTER TABLE "TB_FARMACIA" ADD CONSTRAINT "UQ_7737db16f908866a049c1aae729" UNIQUE ("NU_CNPJ")`);
            }
        }
        
        // Alterações de DEFAULT que são idempotentes (podem ser executadas várias vezes)
        await queryRunner.query(`ALTER TABLE "TB_VERIFICACAO" ALTER COLUMN "DT_CRIACAO" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "TB_VERIFICACAO" ALTER COLUMN "DT_ATUALIZACAO" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "TB_USUARIO" ALTER COLUMN "DT_CRIACAO" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "TB_USUARIO" ALTER COLUMN "DT_ATUALIZACAO" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "TB_TRANSACAO_USUARIO" ALTER COLUMN "DT_CRIACAO" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "TB_2FA" ALTER COLUMN "DT_CRIACAO" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "TB_2FA" ALTER COLUMN "DT_ATUALIZACAO" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "TB_FARMACIA" ALTER COLUMN "DT_INCLUSAO" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "TB_FARMACIA" ALTER COLUMN "DT_ALTERACAO" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "TB_ORGANIZACAO" ALTER COLUMN "DT_CRIACAO" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "TB_MEMBRO" ALTER COLUMN "DT_CRIACAO" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "TB_CONVITE" ALTER COLUMN "DT_CRIACAO" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "TB_AUDITORIA" ALTER COLUMN "DT_CRIACAO" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "TB_CONTA" ALTER COLUMN "DT_CRIACAO" SET DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "TB_CONTA" ALTER COLUMN "DT_ATUALIZACAO" SET DEFAULT now()`);
        
        // Verificar se a FK já existe antes de criar (só criar se ambas as tabelas existem)
        const fkExists = await queryRunner.query(`
            SELECT EXISTS (
                SELECT FROM information_schema.table_constraints 
                WHERE constraint_schema = 'public' 
                AND constraint_name = 'FK_07bbfbefb91ab21032726ba72b3'
            );
        `);
        
        if (!fkExists[0].exists && credenciamentoTableExists[0].exists && motivoTableExists[0].exists) {
            await queryRunner.query(`ALTER TABLE "TB_FARMACIA_CREDENCIAMENTO" ADD CONSTRAINT "FK_07bbfbefb91ab21032726ba72b3" FOREIGN KEY ("CO_MOTIVO_CRED") REFERENCES "TB_MOTIVO_CREDENCIAMENTO"("CO_MOTIVO_CRED") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        }
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "TB_FARMACIA_CREDENCIAMENTO" DROP CONSTRAINT "FK_07bbfbefb91ab21032726ba72b3"`);
        await queryRunner.query(`ALTER TABLE "TB_CONTA" ALTER COLUMN "DT_ATUALIZACAO" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "TB_CONTA" ALTER COLUMN "DT_CRIACAO" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "TB_AUDITORIA" ALTER COLUMN "DT_CRIACAO" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "TB_CONVITE" ALTER COLUMN "DT_CRIACAO" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "TB_MEMBRO" ALTER COLUMN "DT_CRIACAO" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "TB_ORGANIZACAO" ALTER COLUMN "DT_CRIACAO" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "TB_FARMACIA" ALTER COLUMN "DT_ALTERACAO" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "TB_FARMACIA" ALTER COLUMN "DT_INCLUSAO" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "TB_FARMACIA" DROP CONSTRAINT "UQ_7737db16f908866a049c1aae729"`);
        await queryRunner.query(`ALTER TABLE "TB_FARMACIA" DROP CONSTRAINT "PK_c25fd48ad34644edccea4dc40df"`);
        await queryRunner.query(`ALTER TABLE "TB_FARMACIA" ADD CONSTRAINT "PK_7524b5e083554075ecaa67cfff5" PRIMARY KEY ("NU_CNPJ", "CO_SEQ_FARMACIA")`);
        await queryRunner.query(`ALTER TABLE "TB_2FA" ALTER COLUMN "DT_ATUALIZACAO" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "TB_2FA" ALTER COLUMN "DT_CRIACAO" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "TB_TRANSACAO_USUARIO" ALTER COLUMN "DT_CRIACAO" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "TB_USUARIO" ALTER COLUMN "DT_ATUALIZACAO" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "TB_USUARIO" ALTER COLUMN "DT_CRIACAO" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "TB_VERIFICACAO" ALTER COLUMN "DT_ATUALIZACAO" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "TB_VERIFICACAO" ALTER COLUMN "DT_CRIACAO" SET DEFAULT CURRENT_TIMESTAMP`);
        await queryRunner.query(`ALTER TABLE "TB_FARMACIA" DROP CONSTRAINT "PK_7524b5e083554075ecaa67cfff5"`);
        await queryRunner.query(`ALTER TABLE "TB_FARMACIA" ADD CONSTRAINT "PK_7737db16f908866a049c1aae729" PRIMARY KEY ("NU_CNPJ")`);
        await queryRunner.query(`ALTER TABLE "TB_FARMACIA" DROP COLUMN "CO_SEQ_FARMACIA"`);
        await queryRunner.query(`COMMENT ON TABLE "TB_FARMACIA_CREDENCIAMENTO" IS NULL`);
        await queryRunner.query(`DROP INDEX "public"."UK_TB_FARMACIA_CRED_CO_FARMACIA"`);
        await queryRunner.query(`DROP TABLE "TB_FARMACIA_CREDENCIAMENTO"`);
        await queryRunner.query(`COMMENT ON TABLE "TB_MOTIVO_CREDENCIAMENTO" IS NULL`);
        await queryRunner.query(`DROP INDEX "public"."IDX_184c3a2d02de0469258582257c"`);
        await queryRunner.query(`DROP TABLE "TB_MOTIVO_CREDENCIAMENTO"`);
    }

}
